// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR-Zt4xnYLxENNIPGyGpEyJjSkOQfK7bc',
    appId: '1:57162308139:web:06eec7c21951313b6aa86e',
    messagingSenderId: '57162308139',
    projectId: 'app-bmi-46e4a',
    authDomain: 'app-bmi-46e4a.firebaseapp.com',
    storageBucket: 'app-bmi-46e4a.firebasestorage.app',
    measurementId: 'G-7Y79GVPXPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmsl_lFHVE7vhT2UUFyZUZazDpaLfOFFQ',
    appId: '1:57162308139:android:b905edb565504aee6aa86e',
    messagingSenderId: '57162308139',
    projectId: 'app-bmi-46e4a',
    storageBucket: 'app-bmi-46e4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHKXb9nW_hh9uqagHapXloV0WxM2-nA0',
    appId: '1:57162308139:ios:be1be4c06374a1676aa86e',
    messagingSenderId: '57162308139',
    projectId: 'app-bmi-46e4a',
    storageBucket: 'app-bmi-46e4a.firebasestorage.app',
    iosBundleId: 'com.example.appBmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmHKXb9nW_hh9uqagHapXloV0WxM2-nA0',
    appId: '1:57162308139:ios:be1be4c06374a1676aa86e',
    messagingSenderId: '57162308139',
    projectId: 'app-bmi-46e4a',
    storageBucket: 'app-bmi-46e4a.firebasestorage.app',
    iosBundleId: 'com.example.appBmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR-Zt4xnYLxENNIPGyGpEyJjSkOQfK7bc',
    appId: '1:57162308139:web:7b9434f32b54265f6aa86e',
    messagingSenderId: '57162308139',
    projectId: 'app-bmi-46e4a',
    authDomain: 'app-bmi-46e4a.firebaseapp.com',
    storageBucket: 'app-bmi-46e4a.firebasestorage.app',
    measurementId: 'G-D7S5MJ9FH5',
  );
}
